import streamlit as st 
st.title("ISHANK GERA")
st.image("ishank12.jpg", width = 500)
st.title("HELLO , I'm Ishank")
st.subheader("I am currently pursuing my B.Tech from Dronacharya college of Engineering , Gurugram")
st.subheader("I am a passionate guy having confidence in my skills and knowledge")
st.header("Internships:")
st.subheader("- Full Stack development trainee and intern at innomatics reasearch labs")
st.subheader("- Data Science intern trainee and intern at innomatics reasearch labs")
st.subheader("- Technical Content Writer at GeeksforGeeks")
st.header(":orange[Educational background]")
st.subheader("BTech CSE(AI ML) (CGPA : 9.13 / 10)")
st.subheader("Class XII - Jain Public School, Rewari (91.8%)")
st.subheader("Class X - Jain Public School, Rewari (87%)")
st.header(":red[Skills]")
st.subheader("- C++")
st.subheader("- Data Structure and Algorithms")
st.subheader("- Python")
st.subheader("- Javascript")
st.subheader("*I am currenly learning python for Data Science and Backend Development")
st.header(":blue[Projects]")
st.subheader("- Myntra clone using HTML and CSS")
st.subheader("- Heart Disease prediction model using Machine Learning") 
st.header(":pink[Coding profiles]")
st.subheader("https://leetcode.com/Ishank_Gera27/")
st.subheader("https://github.com/IshankGera")
st.subheader("https://auth.geeksforgeeks.org/user/geraishank27/practice/")
st.header("Achievements")
st.subheader("- Achieved top 10""% ""rank in both Data science and Full stack development assessment exam for internship at innomatics research labs")
st.subheader("- State Level Cricket player")
st.subheader("Connect Me:")
st.subheader("geraishank9@gmail.com")
st.subheader("http://linkedin.com/in/ishank-gera-74a78a244")


